name: Issue Autoresponse

on:
  issues:
    types: [opened]

jobs:
  auto-response:
    runs-on: ubuntu-latest

    steps:
    - uses: derekprior/add-autoresponse@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        respondableId: ${{ github.event.issue.node_id }}
        response: "_GitHub staff are eager to continue in conversations and knowledge-sharing with you. We invite you to head over to [Feedback Discussions](https://github.com/github/feedback/discussions) and share your product feedback and questions directly with us (noted [here](https://github.com/isaacs/github#important-note-github-now-has-an-official-feedback-repository-open-a-discussion-there-to-ask-questions-or-discuss-bugs-this-repo-is-deprecated)). Once you have added your thoughts in Feedback Discussions, we ask that you close this newly-created issue. Otherwise, we will keep this issue open for the next 7 days, then will close it._"
        author: ${{ github.event.issue.user.login }}
